### ISSUE TITLE
Installation is not clear

### ISSUE THREAD

**Issue by shashankgoudp** [SoftwareEngineeringToolDemos/FSE-2011-PSPWizard#3]
There is no mention about the netbeans in the installation.txt

**Comment by mverma4** [comment]
![screen shot 2015-10-20 at 11 52 01 am](https://cloud.githubusercontent.com/assets/13962304/10612949/0e58b8a2-7721-11e5-9119-67ee21f87580.png)

**Comment by mverma4** [comment]
Updated the VM Installation.txt to mention the version of Netbeans IDE Required thanks!
